version: '3'
services:
  web:
    hostname: helloprint-consumer

    build: .

    image: helloprint-consumer-app

    ports:
        - 4200:80

    volumes:
      - .:/var/www/html

    depends_on:
      - db

    links:
      - db

  db:
    image: mysql:5.7

    ports:
      - 4201:3306

    environment:
      MYSQL_ROOT_PASSWORD: rootpass

    volumes:
        - ./sql:/tmp/database

    command: mysqld --init-file="/tmp/database/install_db.sql"